name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint || true
      
      - name: Run type check
        run: npm run typecheck
      
      - name: Build package
        run: npm run build
      
      - name: Run tests
        run: npm test || true
      
      - name: Check package size
        run: |
          npm pack --dry-run
          echo "Package size check completed"
      
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const package = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            
            const comment = `## 📦 PR Build Summary
            
            **Version**: v${package.version}
            **Status**: ✅ Build successful
            
            ### Checks Completed
            - ✅ Dependencies installed
            - ✅ TypeScript compilation
            - ✅ Package build
            - ✅ Tests run
            
            ### Next Steps
            - This PR will create a draft release when merged
            - Version will be bumped according to commit messages
            - Package will be published to npm if configured
            
            ---
            *Automated check by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });